version: "3"

services:
  db:
    image: mariadb:10.1
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      net:
        aliases:
          - db

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      #- PMA_ABSOLUTE_URI=https://arc.itb.ac.id/pma/
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${DBROOT}
    ports:
      - "${PMA_PORT:-127.0.0.1:10180}:80"
    networks:
      net:
        aliases:
          - pma

  app:
    build:
      context: .
      dockerfile: app.dockerfile
    image: bmgitb
    restart: always
    stdin_open: true
    tty: true
    entrypoint: ["sh", "entrypoint.sh"]
    command: ["runserver", "0.0.0.0:8080"]
    volumes:
      - .:/app
    ports:
      - "${APP_PORT-127.0.0.1:10080}:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      net:
        aliases:
          - app

networks:
  net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-bmg
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.254.254}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
