version: "3"

services:
  database:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env

  bmgitb:
    build: .
    image: bmgitb
    stdin_open: true
    tty: true
    entrypoint: ["bash", "entrypoint.sh"]
    command: ["runserver", "0.0.0.0:8080"]
    volumes:
      - ./:/bmgitb
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - database
