#!/bin/bash

if [ ! -d 'migrations' ]; then
python manage.py makemigrations main
python manage.py migrate
python manage.py syncdb --noinput
echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@itb.ac.id', 'passukan')" | python manage.py shell
fi

python manage.py $@
