openapi: 3.0.0
info:
  title: BMG API
  version: 1.0.0
servers:
  - url: http://localhost:8000/main
    description: Current
security:
  - access_token: []
paths:
  /pasien/:
    post:
      tags:
        - pasien
      summary: create new pasien
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pasien'
      responses:
        200:
          description: pasien created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralOkProperties'
    get:
      tags:
        - pasien
      summary: get list of pasien data
      parameters: 
        - name: nama
          in: query
          required: false
          schema:
            type: string
            example: "Bambang"
        - name: kategori
          in: query
          required: false
          schema:
            type: string
            enum: ["Umum", "Mahasiswa", "Karyawan BMG", "Karyawan ITB", "Keluarga Karyawan ITB", "Mitra Kerja Sama"]
        - name: nomor_kartu_identitas
          in: query
          required: false
          schema:
            type: string
            example: "13516082"
      responses:
        200:
          description: list fetched
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/GeneralOkProperties'
                  - properties:
                      pasien:
                        type: array
                        items:
                          $ref: '#/components/schemas/pasien'
  /pasien/{no_pasien}/:
    get:
      tags:
        - pasien
      parameters:
        - name: no_pasien
          in: path
          required: true
          schema:
            type: string
            example: "P-1234"
      summary: get individual pasien data
      responses:
        200:
          description: list fetched
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/GeneralOkProperties'
                  - $ref: '#/components/schemas/pasien'
    patch:
      tags:
        - pasien
      parameters:
        - name: no_pasien
          in: path
          required: true
          schema:
            type: string
            example: "P-1234"
      summary: update pasien
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pasien'
      responses:
        200:
          description: pasien created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralOkProperties'      
  /user/authenticate/:
    post:
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "loket"
                password:
                  type: string
                  example: "loket"
      responses:
        200:
          description: user recognized
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: "2io1mwqkmedqwke"
  /klinik/kunjungan/:
    post:
      tags:
        - kunjungan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                kunjungan:
                  $ref: '#/components/schemas/kunjungan'
      responses:
        200:
          description: pasien created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralOkProperties'
    get:
      tags:
        - kunjungan
      parameters: 
        - in: query
          name: kode
          schema:
            type: string
            example: "Ku-123213"
          required: false
        - in: query
          name: pasien__nama
          schema:
            type: string
            example: "Robert"
          required: false
        - in: query
          name: dokter__nama
          schema:
            type: string
            example: "Bambang"
          required: false
      responses:
        200:
          description: kunjungan list fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  kunjungan:
                    type: array
                    items:
                      $ref: '#/components/schemas/kunjungan'
  /klinik/kunjungan/{kode_kunjungan}:
    get:
      tags:
        - kunjungan
      parameters: 
        - in: path
          name: kode_kunjungan
          schema:
            type: string
            example: "Ku-123213"
          required: true
      responses:
        200:
          description: kunjungan list fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  kunjungan:
                    $ref: '#/components/schemas/kunjungan'
  /apotek/resep/:
    post:
      tags:
        - apotek
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pembelian_resep'
      responses:
        200:
          description: pembelian resep created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralOkProperties'
    get:
      tags:
        - apotek
      parameters: 
        - in: query
          name: pasien__nama
          schema:
            type: string
            example: "Robert"
        - in: query
          name: obat__obat__kode
          schema:
            type: string
            example: "O-12312"
        - in: query
          name: tarif
          schema:
            type: integer
            example: 1323
      responses:
        200:
          description: pembelian resep fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  pembelian_resep:
                    type: array
                    items:
                      $ref: '#/components/schemas/pembelian_resep'
  /apotek/otc/:
    post:
      tags:
        - apotek
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pembelian_otc'
      responses:
        200:
          description: pembelian resep created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralOkProperties'
    get:
      tags:
        - apotek
      parameters: 
        - in: query
          name: obat__obat__kode
          schema:
            type: string
            example: "O-12312"
        - in: query
          name: tarif
          schema:
            type: integer
            example: 1323
      responses:
        200:
          description: pembelian resep fetched
          content:
            application/json:
              schema:
                type: object
                properties:
                  pembelian_resep:
                    type: array
                    items:
                      $ref: '#/components/schemas/pembelian_otc'
components:
  securitySchemes:
    access_token:
      type: apiKey
      in: header
      name: Access-Token
  schemas:
    GeneralOkProperties:
      properties:
        responses:
          type: string
          example: "SUCCESS"
    pasien:
      type: object
      properties:
        no_pasien:
          type: string
          example: "P-1234"
        nama:
          type: string
          example: "Bambang Trikusno"
        tipe_kartu_identitas:
          type: string
          example: "KTP"
        nomor_kartu_identitas:
          type: string
          example: "12392019322329"
        tempat_lahir:
          type: string
          example: "Jakarta"
        tanggal_lahir:
          type: string
          format: date
        gender:
          type: string
          enum: ["Laki-laki", "Perempuan"]
        email:
          type: string
          example: "bambang@trikusno.com"
        no_telepon:
          type: string
          example: "081293709541"
        no_hp:
          type: string
          example: "081293709541"
        golongan_darah:
          type: string
          enum: ["A", "B", "AB", "O"]
        rhesus:
          type: string
          enum: ["+", "-"]
        catatan:
          type: string
          example: "Pasien alergi kacang"
        alamat:
          type: string
          example: "Jl. Cisitu Baru 10"
        kota:
          type: string
          example: "Bandung"
        kategori:
          type: string
          enum: ["Umum", "Mahasiswa", "Karyawan BMG", "Karyawan ITB", "Keluarga Karyawan ITB", "Mitra Kerja Sama"]
    kunjungan:
      type: object
      properties:
        pasien:
          type: string
          example: "P-213123"
        klinik:
          type: string
          example: "KL-433123"
        dokter:
          type: string
          example: "DK-23213"
        tarif:
          type: integer
          example: 1123
        klaim:
          type: integer
          example: 1000
        cash:
          type: integer
          example: 123
        asal:
          type: string
          example: "Jakarta"
        tindakan:
          type: array
          items:
            type: object
            properties:
              tindakan:
                type: string
                example: "Tk-3134"
              cash:
                type: integer
                example: 32329
              klaim:
                type: integer
                example: 343
        diagnosis:
          type: array
          items:
            type: object
            properties:
              diagnosis:
                type: string
                example: "Di-3231"
    pembelian_resep:
      type: object
      properties:
        pasien:
          type: string
          example: "P-23123"
        tarif:
          type: integer
          example: 1235
        subsidi:
          type: integer
          example: 1234
        bayar:
          type: integer
          example: 1
        obat:
          type: array
          items:
            type: object
            properties:
              jumlah:
                type: integer
                example: 2
              obat:
                type: string
                example: "O-232"
              tarif:
                type: integer
                example: 2000
    pembelian_otc:
      type: object
      properties:
        tarif:
          type: integer
          example: 1235
        bayar:
          type: integer
          example: 1
        obat:
          type: array
          items:
            type: object
            properties:
              jumlah:
                type: integer
                example: 2
              obat:
                type: string
                example: "O-232"
              tarif:
                type: integer
                example: 2000