# Generated by Django 2.1.7 on 2019-02-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori_Pasien',
            fields=[
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok_Pasien',
            fields=[
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Kategori_Pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Klinik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baru', models.BooleanField(default=False)),
                ('asal', models.CharField(max_length=100)),
                ('tarif', models.IntegerField()),
                ('subsidi', models.IntegerField()),
                ('bayar', models.IntegerField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis')),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dokter')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=100, unique=True)),
                ('strata', models.CharField(max_length=100)),
                ('internasional', models.BooleanField()),
                ('tpb', models.BooleanField()),
                ('program_studi', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jumlah_stok', models.IntegerField()),
                ('keterangan', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pasien', models.CharField(max_length=100, null=True)),
                ('nama', models.CharField(max_length=255)),
                ('catatan', models.CharField(max_length=800, null=True)),
                ('tipe_kartu_identitas', models.CharField(max_length=100)),
                ('nomor_kartu_identitas', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tanggal_lahir', models.DateField(verbose_name='tanggal lahir')),
                ('alamat', models.CharField(max_length=800)),
                ('kota', models.CharField(max_length=100)),
                ('active', models.CharField(default='active', max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('no_telepon', models.CharField(max_length=100, null=True)),
                ('no_hp', models.CharField(max_length=100, null=True)),
                ('berat_badan', models.IntegerField(null=True, verbose_name='berat badan')),
                ('tinggi_badan', models.IntegerField(null=True, verbose_name='tinggi badan')),
                ('organisasi', models.CharField(max_length=100, null=True)),
                ('golongan_darah', models.CharField(max_length=100, null=True)),
                ('rhesus', models.CharField(max_length=100, null=True)),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Kelompok_Pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=100, unique=True)),
                ('no_pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resep', models.BooleanField(default=False)),
                ('tarif', models.IntegerField()),
                ('subsidi', models.IntegerField()),
                ('bayar', models.IntegerField()),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien')),
            ],
        ),
        migrations.CreateModel(
            name='PembelianObat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Obat')),
                ('pembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pembelian')),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='no_pasien',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien'),
        ),
        migrations.AddField(
            model_name='kunjungan',
            name='no_pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien'),
        ),
        migrations.AddField(
            model_name='dokter',
            name='klinik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Klinik'),
        ),
    ]
