# Generated by Django 2.1.7 on 2019-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidi_obat',
            name='nama',
        ),
        migrations.AddField(
            model_name='subsidi_kunjungan',
            name='keterangan',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
