# Generated by Django 2.2 on 2019-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidi_obat',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='subsidi_tindakan',
            name='kode',
        ),
        migrations.AddField(
            model_name='parameter_subsidi_kunjungan',
            name='kode',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasien',
            name='kategori',
            field=models.CharField(choices=[('Mahasiswa', 'Mahasiswa'), ('Karyawan BMG', 'Karyawan BMG'), ('Karyawan ITB', 'Karyawan ITB'), ('Keluarga Karyawan ITB', 'Keluarga Karyawan ITB'), ('Umun', 'Umum'), ('Mitra Kerja Sama', 'Mitra Kerja Sama')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subsidi_kunjungan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='subsidi_obat',
            name='keterangan',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='subsidi_tindakan',
            name='keterangan',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
