# Generated by Django 2.1.7 on 2019-02-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunjungan',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tpb',
            field=models.BooleanField(default=False),
        ),
    ]
