# Generated by Django 2.2 on 2019-04-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembelianobatotc',
            old_name='pembelianOTC',
            new_name='pembelian_otc',
        ),
        migrations.RemoveField(
            model_name='pembelianobatresep',
            name='pembelianResep',
        ),
        migrations.AddField(
            model_name='pembelianobatresep',
            name='tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembelianresep',
            name='obat',
            field=models.ManyToManyField(to='main.PembelianObatResep'),
        ),
    ]
