# Generated by Django 2.2 on 2019-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190413_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembelianobatotc',
            name='pembelian_otc',
        ),
        migrations.AddField(
            model_name='pembelianobatotc',
            name='tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pembelianotc',
            name='obat',
            field=models.ManyToManyField(to='main.PembelianObatOTC'),
        ),
    ]
