# Generated by Django 2.1.7 on 2019-03-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190324_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter_subsidi_kunjungan',
            name='kategori_pasien',
            field=models.CharField(max_length=100),
        ),
    ]
