# Generated by Django 2.1.7 on 2019-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190228_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='internasional',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='tpb',
            field=models.CharField(max_length=100),
        ),
    ]
