# Generated by Django 2.2 on 2019-09-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190925_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tindakan',
            name='is_cash',
        ),
        migrations.AlterField(
            model_name='tindakan',
            name='is_subsidi',
            field=models.BooleanField(),
        ),
    ]
