# Generated by Django 2.1.7 on 2019-03-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190228_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunjungan',
            name='baru',
            field=models.CharField(default='False', max_length=100),
        ),
    ]
