# Generated by Django 2.1.7 on 2019-03-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190324_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter_subsidi_kunjungan',
            name='keterangan',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
