# Generated by Django 2.2 on 2019-09-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190925_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subsidi_kunjungan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subsidi_obat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subsidi_tindakan',
            name='id',
        ),
        migrations.AddField(
            model_name='subsidi_kunjungan',
            name='subsidi_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Subsidi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidi_obat',
            name='subsidi_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Subsidi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidi_tindakan',
            name='subsidi_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Subsidi'),
            preserve_default=False,
        ),
    ]
