# Generated by Django 2.2 on 2019-04-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190413_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelianresep',
            name='obat',
            field=models.ManyToManyField(blank=True, null=True, to='main.PembelianObatResep'),
        ),
    ]
