# Generated by Django 2.1.7 on 2019-03-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190308_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokter',
            name='kode',
            field=models.CharField(default='0', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
