# Generated by Django 2.2 on 2019-09-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190925_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidi_obat',
            old_name='max_subsidi_per_pembelian',
            new_name='max_subsidi_per_kunjungan',
        ),
    ]
