# Generated by Django 2.2 on 2019-09-26 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190925_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis_kunjungan',
            name='Diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis_kunjungan',
            name='Diagnosis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Diagnosis'),
            preserve_default=False,
        ),
    ]
