# Generated by Django 2.1.7 on 2019-03-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_kunjungan_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tindakan',
            fields=[
                ('nama', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=800)),
            ],
        ),
    ]
