# Generated by Django 2.2 on 2019-09-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190926_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis_kunjungan',
            old_name='Diagnosis',
            new_name='diagnosis',
        ),
    ]
