# Generated by Django 2.1.7 on 2019-03-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tindakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidi_Kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=800)),
                ('max_subsidi_per_kunjungan', models.IntegerField()),
                ('sisa_subsidi', models.IntegerField()),
                ('kunjungan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Kunjungan')),
                ('pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidi_Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=800)),
                ('max_subsidi_per_pembelian', models.IntegerField()),
                ('sisa_subsidi', models.IntegerField()),
                ('pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien')),
                ('pembelian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pembelian')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidi_Tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=800)),
                ('max_subsidi_per_tindakan', models.IntegerField()),
                ('sisa_subsidi', models.IntegerField()),
                ('pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien')),
                ('tindakan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Tindakan')),
            ],
        ),
    ]
