# Generated by Django 2.1.7 on 2019-03-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subsidi_kunjungan_subsidi_obat_subsidi_tindakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('kode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('keterangan', models.CharField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='kunjungan',
            name='koreksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Kunjungan'),
        ),
        migrations.AddField(
            model_name='obat',
            name='harga_otc',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obat',
            name='harga_resep',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resep',
            name='obat',
            field=models.ManyToManyField(null=True, to='main.Obat'),
        ),
    ]
