# Generated by Django 2.1.7 on 2019-03-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190308_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunjungan',
            name='subsidi',
        ),
    ]
