# Generated by Django 2.1.7 on 2019-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_kunjungan_subsidi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resep',
            name='obat',
            field=models.ManyToManyField(to='main.Obat'),
        ),
    ]
