# Generated by Django 2.1.7 on 2019-03-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190308_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran_Tindakan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(max_length=100)),
                ('total_bayar', models.IntegerField()),
                ('subsidi_terpakai', models.IntegerField()),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Kunjungan')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidi_Klinik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=800)),
                ('max_subsidi_per_kunjungan', models.IntegerField()),
                ('sisa_subsidi_bulan_ini', models.IntegerField()),
                ('sisa_subsidi_tahunan', models.IntegerField()),
                ('klinik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Klinik')),
                ('pasien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Pasien')),
            ],
        ),
        migrations.RemoveField(
            model_name='subsidi_kunjungan',
            name='kunjungan',
        ),
        migrations.RemoveField(
            model_name='subsidi_kunjungan',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='subsidi_tindakan',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='subsidi_tindakan',
            name='tindakan',
        ),
        migrations.RenameField(
            model_name='subsidi_obat',
            old_name='sisa_subsidi',
            new_name='sisa_subsidi_bulan_ini',
        ),
        migrations.AddField(
            model_name='subsidi_obat',
            name='sisa_subsidi_tahunan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tindakan',
            name='tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Subsidi_Kunjungan',
        ),
        migrations.DeleteModel(
            name='Subsidi_Tindakan',
        ),
        migrations.AddField(
            model_name='pembayaran_tindakan',
            name='tindakan',
            field=models.ManyToManyField(to='main.Tindakan'),
        ),
    ]
