# Generated by Django 2.1.7 on 2019-03-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190308_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis_Kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnosis', models.ManyToManyField(to='main.Diagnosis')),
                ('kunjungan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Kunjungan')),
            ],
        ),
        migrations.RenameModel(
            old_name='Pembayaran_Tindakan',
            new_name='Tindakan_Kunjungan',
        ),
        migrations.RemoveField(
            model_name='pembelianobat',
            name='obat',
        ),
        migrations.AddField(
            model_name='pembelianobat',
            name='obat',
            field=models.ManyToManyField(to='main.Obat'),
        ),
    ]
